# Custom Language File for Launcher Customizer

[ejs.app]
title = "AzaCraft Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "WILLKOMMEN BEI AZACRAFT"
welcomeDescription = "Azacraft ist ein Community-Server für gemeinsames Spielen, Abenteuer und Spaß. Hier geht es nicht um ein riesiges Projekt, sondern um eine gemütliche Runde unter Freunden."
welcomeDescCTA = "Starte jetzt und werde Teil unserer Community!"

