[ejs.landing]
updateAvailableTooltip = "Update verfügbar"
usernamePlaceholder = "Benutzername"
usernameEditButton = "Bearbeiten"
settingsTooltip = "Einstellungen"
serverStatus = "SERVER"
serverStatusPlaceholder = "OFFLINE"
mojangStatus = "MOJANG-STATUS"
mojangStatusTooltipTitle = "Dienste"
mojangStatusNETitle = "Nicht&nbsp;Wesentliches"
newsButton = "NEWS"
launchButton = "SPIELEN"
launchButtonPlaceholder = "&#8226; Kein Server ausgewählt"
launchDetails = "Bitte warten.."
newsNavigationStatus = "{currentPage} von {totalPages}"
newsErrorLoadSpan = "Suche nach Neuigkeiten.."
newsErrorFailedSpan = "News konnten nicht geladen werden"
newsErrorRetryButton = "Erneut versuchen"
newsErrorNoneSpan = "Keine News"

[ejs.login]
loginCancelText = "Abbrechen"
loginSubheader = "MINECRAFT-ANMELDUNG"
loginEmailError = "* Ungültiger Wert"
loginEmailPlaceholder = "E-MAIL ODER BENUTZERNAME"
loginPasswordError = "* Erforderlich"
loginPasswordPlaceholder = "PASSWORT"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "Passwort vergessen?"
loginRememberMeText = "Angemeldet bleiben?"
loginButtonText = "ANMELDEN"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Benötigst du ein Konto?"
loginPasswordDisclaimer1 = "Dein Passwort wird direkt an Mojang gesendet und niemals gespeichert."
loginPasswordDisclaimer2 = "{appName} ist nicht mit Mojang AB verbunden."

[ejs.loginOptions]
loginOptionsTitle = "Anmeldeoptionen"
loginWithMicrosoft = "Mit Microsoft anmelden"
loginWithMojang = "Mit Mojang anmelden"
cancelButton = "Abbrechen"

[ejs.overlay]
serverSelectHeader = "Verfügbare Server"
serverSelectConfirm = "Auswählen"
serverSelectCancel = "Abbrechen"
accountSelectHeader = "Wähle ein Konto aus"
accountSelectConfirm = "Auswählen"
accountSelectCancel = "Abbrechen"

[ejs.settings]
navHeaderText = "Einstellungen"
navAccount = "Konto"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "Über"
navUpdates = "Updates"
navDone = "Fertig"
tabAccountHeaderText = "Kontoeinstellungen"
tabAccountHeaderDesc = "Füge neue Konten hinzu oder verwalte bestehende."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Microsoft-Konto hinzufügen"
mojangAccount = "Mojang"
addMojangAccount = "+ Mojang-Konto hinzufügen"
minecraftTabHeaderText = "Minecraft-Einstellungen"
minecraftTabHeaderDesc = "Optionen bezüglich des Spielstarts."
gameResolutionTitle = "Spielauflösung"
launchFullscreenTitle = "Im Vollbildmodus starten."
autoConnectTitle = "Beim Start automatisch mit dem Server verbinden."
launchDetachedTitle = "Spielprozess losgelöst vom Launcher starten."
launchDetachedDesc = "Wenn das Spiel nicht losgelöst wird, schließt das Schließen des Launchers auch das Spiel."
tabModsHeaderText = "Mod-Einstellungen"
tabModsHeaderDesc = "Aktiviere oder deaktiviere Mods."
switchServerButton = "Wechseln"
requiredMods = "Benötigte Mods"
optionalMods = "Optionale Mods"
dropinMods = "Drop-in-Mods"
addMods = "Mods hinzufügen"
dropinRefreshNote = "(F5 zum Aktualisieren)"
shaderpacks = "Shaderpacks"
shaderpackDesc = "Aktiviere oder deaktiviere Shader. Bitte beachte, dass Shader nur auf leistungsstarken Systemen flüssig laufen. Du kannst hier eigene Pakete hinzufügen."
selectShaderpack = "Shaderpack auswählen"
tabJavaHeaderText = "Java-Einstellungen"
tabJavaHeaderDesc = "Verwalte die Java-Konfiguration (erweitert)."
memoryTitle = "Arbeitsspeicher"
maxRAM = "Maximaler RAM"
minRAM = "Minimaler RAM"
memoryDesc = "Der empfohlene Mindest-RAM beträgt 3 Gigabyte. Das Einstellen des Minimal- und Maximalwerts auf denselben Wert kann Verzögerungen reduzieren."
memoryTotalTitle = "Gesamt"
memoryAvailableTitle = "Verfügbar"
javaExecutableTitle = "Ausführbare Java-Datei"
javaExecSelDialogTitle = "Ausführbare Java-Datei auswählen"
javaExecSelButtonText = "Datei auswählen"
javaExecDesc = "Die ausführbare Java-Datei wird vor dem Spielstart überprüft."
javaPathDesc = "Der Pfad sollte mit <strong>{pathSuffix}</strong> enden."
jvmOptsTitle = "Zusätzliche JVM-Optionen"
jvmOptsDesc = "Optionen, die der JVM zur Laufzeit übergeben werden. <em>-Xms</em> und <em>-Xmx</em> sollten nicht enthalten sein."
launcherTabHeaderText = "Launcher-Einstellungen"
launcherTabHeaderDesc = "Optionen, die den Launcher selbst betreffen."
allowPrereleaseTitle = "Vorabversion-Updates zulassen."
allowPrereleaseDesc = "Vorabversionen enthalten neue Funktionen, die möglicherweise noch nicht vollständig getestet oder integriert wurden.<br>Dies ist immer aktiviert, wenn du eine Vorabversion verwendest."
dataDirectoryTitle = "Datenverzeichnis"
selectDataDirectory = "Datenverzeichnis auswählen"
chooseFolder = "Ordner auswählen"
dataDirectoryDesc = "Alle Spieldateien und lokalen Java-Installationen werden im Datenverzeichnis gespeichert.<br>Screenshots und Spielstände werden im Instanzordner für die entsprechende Serverkonfiguration gespeichert."
aboutTabHeaderText = "Über"
aboutTabHeaderDesc = "Informationen und Versionshinweise für die aktuelle Version anzeigen."
aboutTitle = "{appName}"
stableRelease = "Stabile Version"
versionText = "Version "
sourceGithub = "Quelle (GitHub)"
support = "Support"
devToolsConsole = "DevTools-Konsole"
releaseNotes = "Versionshinweise"
changelog = "Änderungsprotokoll"
noReleaseNotes = "Keine Versionshinweise"
viewReleaseNotes = "Versionshinweise auf GitHub ansehen"
launcherUpdatesHeaderText = "Launcher-Updates"
launcherUpdatesHeaderDesc = "Updates für den Launcher herunterladen, installieren und überprüfen."
checkForUpdates = "Nach Updates suchen"
whatsNew = "Was ist neu"
updateReleaseNotes = "Update-Versionshinweise"

[ejs.waiting]
waitingText = "Warte auf Microsoft.."

[ejs.welcome]
continueButton = "WEITER"


[js.discord]
waiting = "Warte auf Client.."
state = "Server: {shortId}"

[js.index]
microsoftLoginTitle = "Microsoft-Anmeldung"
microsoftLogoutTitle = "Microsoft-Abmeldung"

[js.login]
login = "ANMELDEN"
loggingIn = "ANMELDEN..."
success = "ERFOLGREICH"
tryAgain = "Erneut versuchen"

[js.login.error]
invalidValue = "* Ungültiger Wert"
requiredValue = "* Erforderlich"

[js.login.error.unknown]
title = "Unbekannter Fehler bei der Anmeldung"
desc = "Ein unbekannter Fehler ist aufgetreten. Bitte überprüfe die Konsole für Details."

[js.landing.launch]
pleaseWait = "Bitte warten.."
failureTitle = "Fehler beim Start"
failureText = "Siehe Konsole (STRG + Shift + i) für weitere Details."
okay = "Okay"

[js.landing.selectedAccount]
noAccountSelected = "Kein Konto ausgewählt"

[js.landing.selectedServer]
noSelection = "Kein Server ausgewählt"
loading = "Laden.."

[js.landing.serverStatus]
server = "SERVER"
offline = "OFFLINE"
players = "SPIELER"

[js.landing.systemScan]
checking = "Prüfe Systeminformationen.."
noCompatibleJava = "Keine kompatible<br>Java-Installation gefunden"
installJavaMessage = "Um Minecraft zu starten, benötigst du eine 64-Bit-Installation von Java {major}. Möchtest du, dass wir eine Kopie installieren?"
installJava = "Java installieren"
installJavaManually = "Manuell installieren"
javaDownloadPrepare = "Java-Download wird vorbereitet.."
javaDownloadFailureTitle = "Fehler beim Java-Download"
javaDownloadFailureText = "Siehe Konsole (STRG + Shift + i) für weitere Details."
javaRequired = "Java wird zum<br>Starten benötigt"
javaRequiredMessage = 'Eine gültige x64-Installation von Java {major} wird zum Starten benötigt.<br><br>Bitte beziehe dich auf unsere <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">Anleitung zur Java-Verwaltung</a> für Anweisungen zur manuellen Installation von Java.'
javaRequiredDismiss = "Ich verstehe"
javaRequiredCancel = "Zurück"

[js.landing.downloadJava]
findJdkFailure = "OpenJDK-Distribution konnte nicht gefunden werden."
javaDownloadCorruptedError = "Das heruntergeladene JDK hat einen fehlerhaften Hash, die Datei könnte beschädigt sein."
extractingJava = "Java wird extrahiert"
javaInstalled = "Java installiert!"

[js.landing.dlAsync]
loadingServerInfo = "Lade Serverinformationen.."
fatalError = "Schwerwiegender Fehler"
unableToLoadDistributionIndex = "Eine Kopie des Distributionsindex konnte nicht geladen werden. Siehe Konsole (STRG + Shift + i) für weitere Details."
pleaseWait = "Bitte warten.."
errorDuringLaunchTitle = "Fehler beim Start"
seeConsoleForDetails = "Siehe Konsole (STRG + Shift + i) für weitere Details."
validatingFileIntegrity = "Überprüfe Dateiintegrität.."
errorDuringFileVerificationTitle = "Fehler bei der Dateiüberprüfung"
downloadingFiles = "Dateien werden heruntergeladen.."
errorDuringFileDownloadTitle = "Fehler beim Herunterladen der Dateien"
preparingToLaunch = "Vorbereitung zum Start.."
launchingGame = "Spiel wird gestartet.."
launchWrapperNotDownloaded = "Die Hauptdatei, LaunchWrapper, konnte nicht korrekt heruntergeladen werden. Daher kann das Spiel nicht starten.<br><br>Um dieses Problem zu beheben, deaktiviere vorübergehend deine Antivirensoftware und starte das Spiel erneut.<br><br>Wenn du Zeit hast, <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">melde bitte ein Problem</a> und teile uns mit, welche Antivirensoftware du verwendest. Wir werden sie kontaktieren und versuchen, die Sache zu klären."
doneEnjoyServer = "Fertig. Viel Spaß auf dem Server!"
checkConsoleForDetails = "Bitte überprüfe die Konsole (STRG + Shift + i) für weitere Details."

[js.landing.news]
checking = "Suche nach Neuigkeiten"

[js.landing.discord]
loading = "Lade Spiel.."
joining = "Segelt nach Westeros!"
joined = "Erkundet das Reich!"

[js.overlay]
dismiss = "Schließen"

[js.settings.fileSelectors]
executables = "Ausführbare Dateien"
allFiles = "Alle Dateien"

[js.settings.mstfLogin]
errorTitle = "Etwas ist schiefgelaufen"
errorMessage = "Microsoft-Authentifizierung fehlgeschlagen. Bitte versuche es erneut."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Etwas ist schiefgelaufen"
errorMessage = "Microsoft-Abmeldung fehlgeschlagen. Bitte versuche es erneut."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Konto auswählen"
selectedButton = "Konto ausgewählt &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Warnung<br>Dies ist dein letztes Konto"
lastAccountWarningMessage = "Um den Launcher zu verwenden, musst du mit mindestens einem Konto angemeldet sein. Du musst dich danach erneut anmelden.<br><br>Bist du sicher, dass du dich abmelden möchtest?"
confirmButton = "Ich bin sicher"
cancelButton = "Abbrechen"

[js.settings.authAccountPopulate]
username = "Benutzername"
uuid = "UUID"
selectAccount = "Konto auswählen"
selectedAccount = "Ausgewähltes Konto ✓"
logout = "Abmelden"

[js.settings.dropinMods]
removeButton = "Entfernen"
deleteFailedTitle = "Fehler beim Löschen<br>des Drop-in-Mods {fullName}"
deleteFailedMessage = "Stelle sicher, dass die Datei nicht verwendet wird, und versuche es erneut."
failedToggleTitle = "Fehler beim Umschalten<br>eines oder mehrerer Drop-in-Mods"
okButton = "Okay"

[js.settings.serverListing]
mainServer = "Hauptserver"

[js.settings.java]
selectedJava = "Ausgewählt: Java {version} ({vendor})"
invalidSelection = "Ungültige Auswahl"
requiresJava = "Benötigt Java {major} x64."
availableOptions = "Verfügbare Optionen für Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Vorabversion"
stableReleaseTitle = "Stabile Version"
releaseNotesFailed = "Versionshinweise konnten nicht geladen werden."

[js.settings.updates]
newReleaseTitle = "Neue Version verfügbar"
newPreReleaseTitle = "Neue Vorabversion verfügbar"
downloadingButton = "Wird heruntergeladen.."
downloadButton = 'Von GitHub herunterladen<span style="font-size: 10px;color: gray;text-shadow: none !important;">Schließe den Launcher und führe die Installationsdatei aus, um zu aktualisieren.</span>'
latestVersionTitle = "Du verwendest die neueste Version"
checkForUpdatesButton = "Nach Updates suchen"
checkingForUpdatesButton = "Suche nach Updates.."

[js.settings.msftLogin]
errorTitle = "Microsoft-Anmeldung fehlgeschlagen"
errorMessage = "Wir konnten dein Microsoft-Konto nicht authentifizieren. Bitte versuche es erneut."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Schwerwiegender Fehler: Distributionsindex konnte nicht geladen werden"
fatalErrorMessage = "Es konnte keine Verbindung zu unseren Servern hergestellt werden, um den Distributionsindex herunterzuladen. Es waren keine lokalen Kopien zum Laden verfügbar. <br><br>Der Distributionsindex ist eine wesentliche Datei, die die neuesten Serverinformationen bereitstellt. Der Launcher kann ohne sie nicht starten. Stelle sicher, dass du mit dem Internet verbunden bist, und starte die Anwendung neu."
closeButton = "Schließen"

[js.uibinder.validateAccount]
failedMessageTitle = "Anmeldung konnte nicht aktualisiert werden"
failedMessage = "Wir konnten die Anmeldung für <strong>{account}</strong> nicht aktualisieren. Bitte wähle ein anderes Konto aus oder melde dich erneut an."
failedMessageSelectAnotherAccount = "Wir konnten die Anmeldung für <strong>{account}</strong> nicht aktualisieren. Bitte melde dich erneut an."
loginButton = "Anmelden"
selectAnotherAccountButton = "Anderes Konto auswählen"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Suche nach Updates..."
installNowButton = "Jetzt installieren"
checkForUpdatesButton = "Nach Updates suchen"

[js.auth.microsoft.error]
noProfileTitle = "Fehler bei der Anmeldung:<br>Profil nicht eingerichtet"
noProfileDesc = "Dein Microsoft-Konto hat noch kein Minecraft-Profil. Wenn du das Spiel kürzlich gekauft oder über den Xbox Game Pass eingelöst hast, musst du dein Profil auf <a href=\"https://minecraft.net/\">Minecraft.net</a> einrichten.<br><br>Wenn du das Spiel noch nicht gekauft hast, kannst du das ebenfalls auf <a href=\"https://minecraft.net/\">Minecraft.net</a> tun."
noXboxAccountTitle = "Fehler bei der Anmeldung:<br>Kein Xbox-Konto"
noXboxAccountDesc = "Mit deinem Microsoft-Konto ist kein Xbox-Konto verknüpft."
xblBannedTitle = "Fehler bei der Anmeldung:<br>Xbox Live nicht verfügbar"
xblBannedDesc = "Dein Microsoft-Konto stammt aus einem Land, in dem Xbox Live nicht verfügbar oder gesperrt ist."
under18Title = "Fehler bei der Anmeldung:<br>Elterliche Zustimmung erforderlich"
under18Desc = "Konten für Benutzer unter 18 Jahren müssen von einem Erwachsenen zu einer Familie hinzugefügt werden."
unknownTitle = "Unbekannter Fehler bei der Anmeldung"
unknownDesc = "Ein unbekannter Fehler ist aufgetreten. Bitte sieh in der Konsole nach Details."

[js.auth.mojang.error]
methodNotAllowedTitle = "Interner Fehler:<br>Methode nicht erlaubt"
methodNotAllowedDesc = "Methode nicht erlaubt. Bitte melde diesen Fehler."
notFoundTitle = "Interner Fehler:<br>Nicht gefunden"
notFoundDesc = "Der Authentifizierungsendpunkt wurde nicht gefunden. Bitte melde dieses Problem."
accountMigratedTitle = "Fehler bei der Anmeldung:<br>Konto migriert"
accountMigratedDesc = "Du hast versucht, dich mit einem migrierten Konto anzumelden. Versuche es erneut mit der E-Mail-Adresse des Kontos als Benutzernamen."
invalidCredentialsTitle = "Fehler bei der Anmeldung:<br>Ungültige Anmeldedaten"
invalidCredentialsDesc = "Die eingegebene E-Mail-Adresse oder das Passwort ist falsch. Bitte versuche es erneut."
tooManyAttemptsTitle = "Fehler bei der Anmeldung:<br>Zu viele Versuche"
tooManyAttemptsDesc = "Es gab in letzter Zeit zu viele Anmeldeversuche mit diesem Konto. Bitte versuche es später erneut."
invalidTokenTitle = "Fehler bei der Anmeldung:<br>Ungültiger Token"
invalidTokenDesc = "Der bereitgestellte Zugriffstoken ist ungültig."
tokenHasProfileTitle = "Fehler bei der Anmeldung:<br>Token hat bereits ein Profil"
tokenHasProfileDesc = "Dem Zugriffstoken ist bereits ein Profil zugewiesen. Die Auswahl von Profilen ist noch nicht implementiert."
credentialsMissingTitle = "Fehler bei der Anmeldung:<br>Anmeldedaten fehlen"
credentialsMissingDesc = "Benutzername/Passwort wurde nicht übermittelt oder das Passwort ist kürzer als 3 Zeichen."
invalidSaltVersionTitle = "Fehler bei der Anmeldung:<br>Ungültige Salt-Version"
invalidSaltVersionDesc = "Ungültige Salt-Version."
unsupportedMediaTypeTitle = "Interner Fehler:<br>Nicht unterstützter Medientyp"
unsupportedMediaTypeDesc = "Nicht unterstützter Medientyp. Bitte melde diesen Fehler."
accountGoneTitle = "Fehler bei der Anmeldung:<br>Konto migriert"
accountGoneDesc = "Das Konto wurde zu einem Microsoft-Konto migriert. Bitte melde dich mit Microsoft an."
unreachableTitle = "Fehler bei der Anmeldung:<br>Nicht erreichbar"
unreachableDesc = "Die Authentifizierungsserver konnten nicht erreicht werden. Stelle sicher, dass sie online und du mit dem Internet verbunden bist."
gameNotPurchasedTitle = "Fehler bei der Anmeldung:<br>Spiel nicht gekauft"
gameNotPurchasedDesc = "Mit dem Konto, mit dem du dich anzumelden versuchst, wurde keine Kopie von Minecraft gekauft. Du kannst eine Kopie auf <a href=\"https://minecraft.net/\">Minecraft.net</a> erwerben."
unknownErrorTitle = "Unbekannter Fehler bei der Anmeldung"
unknownErrorDesc = "Ein unbekannter Fehler ist aufgetreten. Bitte sieh in der Konsole nach Details."